In [2]:
import numpy as np
startarray = np.array([2,4,8,10,12,14])
out = np.vander(startarray, increasing = False)
print(out)

[[    32     16      8      4      2      1]
 [  1024    256     64     16      4      1]
 [ 32768   4096    512     64      8      1]
 [100000  10000   1000    100     10      1]
 [248832  20736   1728    144     12      1]
 [537824  38416   2744    196     14      1]]
